/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package favoritebooks;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */


public class AddBookFrame extends javax.swing.JFrame {
    /**
     * Creates new form AddBook
     */
   
    public AddBookFrame() {
        initComponents();

    }
 
    private void JButtonforcontrolActionPerformed(java.awt.event.ActionEvent evt) {
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textlabel = new javax.swing.JLabel();
        titlelabel = new javax.swing.JLabel();
        categorylabel = new javax.swing.JLabel();
        authorlabel = new javax.swing.JLabel();
        awardlabel = new javax.swing.JLabel();
        ratinglabel = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        button_add = new javax.swing.JButton();
        yearlabel = new javax.swing.JLabel();
        numberofpageslabel = new javax.swing.JLabel();
        descrıptıonlabel = new javax.swing.JLabel();
        titletext_field = new javax.swing.JTextField();
        categorytextfield = new javax.swing.JTextField();
        author_textfield = new javax.swing.JTextField();
        textfieldaward = new javax.swing.JTextField();
        yeartextfield = new javax.swing.JTextField();
        numberofpagestextffield = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textlabel.setText("Please enter the information of the new book to be added =");

        titlelabel.setText("TITLE :");

        categorylabel.setText("CATEGORY :");

        authorlabel.setText("AUTHOR NAME-SURNAME :");

        awardlabel.setText("AWARD :");

        ratinglabel.setText("RATING :");

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        button_add.setText("ADD");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        yearlabel.setText("YEAR : ");

        numberofpageslabel.setText("NUMBER OF PAGES : ");

        descrıptıonlabel.setText("SHORT DESCRIPTION :");

        titletext_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titletext_fieldActionPerformed(evt);
            }
        });

        categorytextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorytextfieldActionPerformed(evt);
            }
        });

        yeartextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeartextfieldActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(categorylabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(categorytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(authorlabel)
                                    .addGap(47, 47, 47)
                                    .addComponent(author_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(yearlabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(yeartextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numberofpageslabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(numberofpagestextffield, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(descrıptıonlabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(awardlabel)
                                        .addComponent(ratinglabel))
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textfieldaward, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titlelabel)
                                .addGap(18, 18, 18)
                                .addComponent(titletext_field, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(textlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlelabel)
                    .addComponent(titletext_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorylabel)
                    .addComponent(categorytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(awardlabel)
                    .addComponent(textfieldaward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratinglabel)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearlabel)
                    .addComponent(yeartextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberofpageslabel)
                    .addComponent(numberofpagestextffield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descrıptıonlabel)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void titletext_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titletext_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titletext_fieldActionPerformed

    private void categorytextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorytextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorytextfieldActionPerformed

    private void yeartextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeartextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yeartextfieldActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        writefile();
    }//GEN-LAST:event_button_addActionPerformed
    
     private void writefile(){
                     

          File file = new File("favoritebooks.txt");
          FileOutputStream fileoutputstream;
            try {
               fileoutputstream = new FileOutputStream(file,true);
              
               String rating =(String) combobox.getSelectedItem();
               fileoutputstream.write((findbookid() + " , ").getBytes());
               fileoutputstream.write((titletext_field.getText() + " , ").getBytes());
               fileoutputstream.write((categorytextfield.getText() + " , ").getBytes());
               fileoutputstream.write((author_textfield.getText() + " , ").getBytes());
               fileoutputstream.write((textfieldaward.getText() + " , ").getBytes());
               fileoutputstream.write((rating + " , ").getBytes());
               fileoutputstream.write((yeartextfield.getText() + " , ").getBytes());
               fileoutputstream.write((numberofpagestextffield.getText() + " , ").getBytes());
               fileoutputstream.write((jTextArea1.getText() + "\n").getBytes());
               fileoutputstream.flush();
               fileoutputstream.close();
               JOptionPane.showMessageDialog(this,"The new book added to favoritebooks.txt .");
            } catch (FileNotFoundException ex) {
                
            } catch (IOException ex) {
            
            }
    }
        public int findbookid() throws FileNotFoundException, IOException{
            
        BufferedReader b = new BufferedReader(new FileReader("favoritebooks.txt"));
        int lines = 1;
        while (b.readLine() != null){
               lines++;
        }
        //System.out.println("ID: "+ lines);
        b.close();
        return lines;
    }
      
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookFrame().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author_textfield;
    private javax.swing.JLabel authorlabel;
    private javax.swing.JLabel awardlabel;
    private javax.swing.JButton button_add;
    private javax.swing.JLabel categorylabel;
    private javax.swing.JTextField categorytextfield;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel descrıptıonlabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel numberofpageslabel;
    private javax.swing.JTextField numberofpagestextffield;
    private javax.swing.JLabel ratinglabel;
    private javax.swing.JTextField textfieldaward;
    private javax.swing.JLabel textlabel;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JTextField titletext_field;
    private javax.swing.JLabel yearlabel;
    private javax.swing.JTextField yeartextfield;
    // End of variables declaration//GEN-END:variables
}
